package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        step {
            type = "rake-runner"
        }
    }
    steps {
        insert(1) {
            step {
                type = "rake-runner"
                param("ui.rakeRunner.rake.trace.invoke.exec.stages.enabled", "true")
                param("ui.rakeRunner.frameworks.testspec.enabled", "true")
                param("ui.rakeRunner.frameworks.shoulda.enabled", "true")
            }
        }
    }
}
